package com.achen.shelf.backfill;

import com.achen.shelf.config.CategoryConfig;
import com.achen.shelf.config.Retailer;
import com.achen.shelf.db.CrawlRunDao;
import com.achen.shelf.db.Database;
import com.achen.shelf.db.PartitionDao;
import java.io.IOException;
import java.io.StringReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.YearMonth;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import org.postgresql.PGConnection;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Writes a synthetic daily price history behind every offer the crawl has really observed.
 *
 * <p>For each offer at the category's retailers with at least one observed price and no synthetic
 * history yet, one observation per day at noon UTC for {@code days} days, ending the day before the
 * category's earliest real observation — so synthetic rows never share an instant with real ones —
 * generated by {@link SyntheticSeries} from the offer's first observed price. Every row is written
 * with {@code source = 'synthetic'}, under a {@code crawl_runs} row of kind {@code backfill} that
 * spans the window it wrote.
 *
 * <p>One transaction, loaded with {@code COPY}: it is all there or none of it is. Re-running it
 * writes nothing for offers that already have synthetic rows and fills in any that gained real
 * observations since, so it converges. Rollups are not recomputed here — run {@code shelf rollup}
 * after.
 */
public final class SyntheticBackfill {

  private static final Logger log = LoggerFactory.getLogger(SyntheticBackfill.class);
  private static final LocalTime NOON = LocalTime.NOON;
  private static final DateTimeFormatter STAMP =
      DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss'+00'");
  private static final int OFFERS_PER_COPY = 500;

  /** What a backfill wrote. */
  public record Summary(
      String category,
      Long runId,
      LocalDate from,
      LocalDate toExclusive,
      int offers,
      long rows,
      Duration took) {}

  private record Anchor(long offerId, int priceCents) {}

  private final Database db;
  private final long seed;

  public SyntheticBackfill(Database db, long seed) {
    this.db = db;
    this.seed = seed;
  }

  /** Backfills {@code days} days behind the category's real history. */
  public Summary run(CategoryConfig category, int days) throws SQLException {
    if (days < 1) {
      throw new IllegalArgumentException("days must be at least 1");
    }
    List<String> retailers = category.retailers().stream().map(Retailer::name).toList();
    long started = System.nanoTime();
    return db.transaction(
        c -> {
          Instant earliest = earliestObserved(c, retailers);
          if (earliest == null) {
            log.info(
                "backfill for {}: no observed prices yet, nothing to anchor on", category.name());
            return new Summary(category.name(), null, null, null, 0, 0, elapsed(started));
          }
          LocalDate toExclusive = earliest.atOffset(ZoneOffset.UTC).toLocalDate();
          LocalDate from = toExclusive.minusDays(days);
          List<Anchor> anchors = anchors(c, retailers);
          if (anchors.isEmpty()) {
            log.info(
                "backfill for {}: every observed offer already has synthetic history",
                category.name());
            return new Summary(category.name(), null, from, toExclusive, 0, 0, elapsed(started));
          }
          for (YearMonth m = YearMonth.from(from);
              !m.isAfter(YearMonth.from(toExclusive));
              m = m.plusMonths(1)) {
            PartitionDao.ensurePartition(c, m.atDay(1).atTime(NOON).toInstant(ZoneOffset.UTC));
          }
          long runId =
              CrawlRunDao.openBackfill(
                  c,
                  category.name(),
                  from.atTime(NOON).toInstant(ZoneOffset.UTC),
                  toExclusive.minusDays(1).atTime(NOON).toInstant(ZoneOffset.UTC));
          long rows = 0;
          for (int i = 0; i < anchors.size(); i += OFFERS_PER_COPY) {
            rows +=
                copy(
                    c,
                    anchors.subList(i, Math.min(i + OFFERS_PER_COPY, anchors.size())),
                    from,
                    toExclusive,
                    runId);
          }
          Summary summary =
              new Summary(
                  category.name(),
                  runId,
                  from,
                  toExclusive,
                  anchors.size(),
                  rows,
                  elapsed(started));
          log.info(
              "backfill for {}: {} synthetic observation(s) for {} offer(s), {} to {}, run {} in {} ms",
              summary.category(),
              summary.rows(),
              summary.offers(),
              summary.from(),
              summary.toExclusive().minusDays(1),
              summary.runId(),
              summary.took().toMillis());
          return summary;
        });
  }

  private static Duration elapsed(long startedNanos) {
    return Duration.ofNanos(System.nanoTime() - startedNanos);
  }

  /** The earliest real observation at the given retailers. */
  private static Instant earliestObserved(Connection c, List<String> retailers)
      throws SQLException {
    String sql =
        """
        select min(po.observed_at)
        from price_observations po
        join offers o on o.id = po.offer_id
        where o.retailer = any (?) and po.source = 'observed'
        """;
    try (PreparedStatement ps = c.prepareStatement(sql)) {
      ps.setArray(1, c.createArrayOf("text", retailers.toArray()));
      try (ResultSet rs = ps.executeQuery()) {
        rs.next();
        var t = rs.getTimestamp(1);
        return t == null ? null : t.toInstant();
      }
    }
  }

  /** Each observed offer's first observed price, for offers with no synthetic history yet. */
  private static List<Anchor> anchors(Connection c, List<String> retailers) throws SQLException {
    String sql =
        """
        select distinct on (po.offer_id) po.offer_id, po.price_cents
        from price_observations po
        join offers o on o.id = po.offer_id
        where o.retailer = any (?) and po.source = 'observed'
          and not exists (select 1 from price_observations s
                          where s.offer_id = po.offer_id and s.source = 'synthetic')
        order by po.offer_id, po.observed_at
        """;
    try (PreparedStatement ps = c.prepareStatement(sql)) {
      ps.setArray(1, c.createArrayOf("text", retailers.toArray()));
      try (ResultSet rs = ps.executeQuery()) {
        List<Anchor> out = new ArrayList<>();
        while (rs.next()) {
          out.add(new Anchor(rs.getLong(1), rs.getInt(2)));
        }
        return out;
      }
    }
  }

  private long copy(
      Connection c, List<Anchor> anchors, LocalDate from, LocalDate toExclusive, long runId)
      throws SQLException {
    StringBuilder csv = new StringBuilder();
    for (Anchor a : anchors) {
      for (SyntheticSeries.Point p :
          SyntheticSeries.generate(a.offerId(), a.priceCents(), from, toExclusive, seed)) {
        csv.append(a.offerId())
            .append(',')
            .append(STAMP.format(p.day().atTime(NOON)))
            .append(',')
            .append(p.priceCents())
            .append(",0,")
            .append(p.inStock())
            .append(',')
            .append(runId)
            .append(",synthetic\n");
      }
    }
    String sql =
        "copy price_observations"
            + " (offer_id, observed_at, price_cents, shipping_cents, in_stock, crawl_run_id, source)"
            + " from stdin (format csv)";
    try {
      return c.unwrap(PGConnection.class)
          .getCopyAPI()
          .copyIn(sql, new StringReader(csv.toString()));
    } catch (IOException e) {
      throw new SQLException("COPY failed", e);
    }
  }
}
